language: en-US
tone_instructions: ''
early_access: false
enable_free_tier: true
reviews:
  profile: assertive
  poem: false
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: []
    labels: []
    drafts: false
    base_branches:
      - rc
      - beta
      - alpha
      - production
      - next
  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true
  tools: {}
  pre_merge_checks: {}
chat:
  auto_reply: true
  integrations:
    jira:
      usage: auto
    linear:
      usage: auto
knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns: []
  learnings:
    scope: auto
  issues:
    scope: auto
  jira:
    usage: auto
    project_keys: []
  linear:
    usage: auto
    team_keys: []
  pull_requests:
    scope: auto
code_generation:
  docstrings:
    language: en-US
    path_instructions: []
  unit_tests:
    path_instructions: []
